[package]
name = "mesh"
version = "0.1.0"
edition = "2018"

[workspace]
members = ["mesh-sys", "mesh-global"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mesh-sys = { path = "mesh-sys" }
